apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    app: nginx
    env: test
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        env: test
    spec:
      containers:
        - name: nginx-container
          image: nginx
  selector:
    app: nginx
  replicas: 2