apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-container
    env: test
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      requests:
        cpu: 256m
        memory: 256Mi
      limits:
        cpu: 256m
        memory: 256Mi
  - name: busybox-container
    image: busybox
    resources:
      requests:
        cpu: 256m
        memory: 256Mi
      limits:
        cpu: 256m
        memory: 256Mi
    command: 
    - "sleep"
    - "100"