apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
    env: test
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        env: test
    spec:
      containers:
        - name: nginx-container
          image: nginx
  selector:
    matchLabels:
      app: nginx
  replicas: 2