apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-rq
  namespace: test
spec:
  hard:
    pods: 10
    requests.cpu: 512m
    requests.memory: 512Mi
    limits.cpu: 1024m
    limits.memory: 1024Mi