apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: test
  labels:
    app: nginx
    env: test
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 512m
        memory: 512Mi
